### ISSUE TITLE
Q: Open source contribution

### ISSUE THREAD

**Issue by lazyfuhrer** [Sindri-Labs/sindri-js#33]
Hi, Is this project open for external contributions @sangaline ? I'd like to contribute. Thanks.

**Comment by sangaline** [comment]
Thanks for your interest! We're still rounding out the basic structure of the project at this point, and there will be some significant additions and refactoring before we reach a non-alpha release. It's a little early to take major outside contributions because of that, but there will definitely be good starting issues for new contributors in the future after things are more stabilized. In the meantime, opening issues for any bug reports or other problems is a great way to contribute.

**Comment by lazyfuhrer** [comment]
Understood, eagerly anticipating future opportunities for contribution. Thank you for the update.
